### ISSUE TITLE
ET-1

### ISSUE THREAD

**Issue by EvgenijTkachuk** [vldm/stegos_explorer#3]
1. Сколько активных нод
2. Циркулейт
3. Цену
4. Капитализацию
5. Пул лотереи, время с последнего выигрыша
6. Количество транзакций в сутки, неделю, месяц
7. Высоту цепочки / номер блока
8. Инфа о предстоящем апгрейде / хардфорке / сжигании и т.п.

**Comment by vldm** [comment]
Спасибо за идеи, я создал для каждого пункта, так как не понятно сколько потребуется на выполнение каждого, но отслежитьва выполнение надо. По этому закрою эту таску.
(I have created a placeholder task for each point.)
